jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8086
   servlet:
      context-path: /
      session:
         timeout: 21600s

spring:
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:~/inventario
      username: sa
      password:
      hikari:
         poolName: pool
         connection-test-query: SELECT 1 FROM DUAL
         connection-timeout: 600000
         maximum-pool-size: 500
         max-lifetime: 1800000
         minimum-idle: 20
         validation-timeout: 3000
         idle-timeout: 60000
         connection-init-sql: SET NAMES utf8mb4
